# YOLOv5 ğŸš€ by Ultralytics, GPL-3.0 license

# Parameters
nc: 45  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple
anchors:
  - [ 5,6, 7,8, 9,10]  # P3/8
  - [ 12,12, 10,18, 15,15]  # P4/16
  - [ 20,20, 26,26, 38,37]  # P5/32


# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 6, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 1, 1]],  # 7-P5/32
   [-1, 3, C4STB, [1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
  ]

# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 2], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # # å¯¹åº”çš„æ£€æµ‹ç‰¹å¾å›¾å¤§å°ä¸º160X160ï¼Œç”¨äºæ£€æµ‹å¤§å°åœ¨4X4ä»¥ä¸Šçš„ç›®æ ‡

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # å¯¹åº”çš„æ£€æµ‹ç‰¹å¾å›¾å¤§å°ä¸º80X80ï¼Œç”¨äºæ£€æµ‹å¤§å°åœ¨8X8ä»¥ä¸Šçš„ç›®æ ‡

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # å¯¹åº”çš„æ£€æµ‹ç‰¹å¾å›¾å¤§å°ä¸º40X40ï¼Œç”¨äºæ£€æµ‹å¤§å°åœ¨16X16ä»¥ä¸Šçš„ç›®æ ‡

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
